### ISSUE TITLE
Issue with request queue listeners

### ISSUE THREAD

**Issue by mjruggiero** [JacORB/JacORB#201]
I just started on a project at work using JacORB 2.3.1. I was trying to update it to the latest version (JacORB 3.8) and noticed that I was getting errors related to request queue listeners.
We are using the jacorb.poa.queue_listeners property to set our listener class which is dynamically created at runtime.
I did some research and found out the problem is occurring in the org.jacorb.poa.RequestQueue class.  The config = true flag in the configure method was being set after the listeners are instantiated.  This was causing addRequestQueueListener to throw an exception.  I traced the history to JacORB 3.0 where the bug was introduced.  The flag was set before the classes were instantiated via reflection.  Since this bug has been around for a while, I'm guessing no one is using this feature except my project.

**Comment by rnc** [comment]
Thanks for the report ; pull requests welcome :-D

**Comment by mjruggiero** [comment]
Sorry, I'm sorta new to GitHub so when I figure out how to do that I will
fix the issue myself.

**Comment by rnc** [comment]
Fixed by #202
