### ISSUE TITLE
UtcTHelper.insert method not working correctly

### ISSUE THREAD

**Issue by egcodes** [JacORB/JacORB#207]
The code is as follows. i use jacorb-3.9 lib.
Result, u object is null.
```
filterable[2] = new Property();
filterable[2].name = EVENT_TIME;
filterable[2].value = orb.create_any();
UtcT u = new UtcT(12, 34, (short)56, (short)78);
UtcTHelper.insert(filterable[2].value, u);
```

> 
> java.lang.NullPointerException
> 	at com.sun.corba.se.impl.corba.AnyImpl.write_value(AnyImpl.java:610)
> 	at com.sun.corba.se.impl.encoding.CDROutputStream_1_0.write_any(CDROutputStream_1_0.java:591)
> 	at com.sun.corba.se.impl.encoding.CDROutputStream.write_any(CDROutputStream.java:220)
> 	at org.omg.CosNotification.PropertyHelper.write(PropertyHelper.java:70)
> 	at org.omg.CosNotification.PropertySeqHelper.write(PropertySeqHelper.java:78)
> 	at org.omg.CosNotification.StructuredEventHelper.write(StructuredEventHelper.java:70)
> 	at org.omg.CosNotifyComm._StructuredPushConsumerStub.push_structured_event(_StructuredPushConsumerStub.java:117)

**Comment by rnc** [comment]
Creating a JUnit test with
```
   import org.omg.TimeBase.UtcT;
   import org.omg.TimeBase.UtcTHelper;
   ...
    @Test
    public void testInsert() throws Exception
    {
        Property filterable[] = new Property[1];
        filterable[0] = new Property();
        filterable[0].name = "EVENT_TIME";
        filterable[0].value = getORB().create_any();
        UtcT u = new UtcT(12, 34, (short) 56, (short) 78);
        UtcTHelper.insert(filterable[0].value, u);
    }
```
the test passes for me. Can you update the test to show the failure?

**Comment by egcodes** [comment]
I get nullpointerexception error when trying to get any object. I think, insert method insert null to filterable[0].value.

`import java.util.Date;
import java.util.Properties;
import org.omg.CORBA.Any;
import org.omg.CosNotification.Property;
import org.omg.TimeBase.UtcT;
import org.omg.TimeBase.UtcTHelper;

public class Testing {

    public static org.omg.CORBA.ORB orb;
    public static Property filterable[];

    public static void main(String[] args) throws Exception {
        Properties properties = System.getProperties();
        orb = org.omg.CORBA.ORB.init(args, properties);

        testInsert();
        testGet();
    }

    public static void testInsert() throws Exception {
        filterable = new Property[1];
        filterable[0] = new Property();
        filterable[0].name = "EVENT_TIME";
        filterable[0].value = orb.create_any();
        UtcT u = new UtcT(12, 34, (short) 56, (short) 78);
        UtcTHelper.insert(filterable[0].value, u);
    }

    public static void testGet() {
        Any any = filterable[0].value;
        UtcT utcT = UtcTHelper.extract(any);
        System.out.println(new Date(System.currentTimeMillis() - org.jacorb.util.Time.millisTo(utcT)));
    }
}`
> Exception in thread "main" java.lang.NullPointerException
	at com.sun.corba.se.impl.corba.AnyImpl.create_input_stream(AnyImpl.java:538)
	at org.omg.TimeBase.UtcTHelper.extract(UtcTHelper.java:37)
	at Testing.testGet(Testing.java:33)
	at Testing.main(Testing.java:19)

**Comment by egcodes** [comment]
@rnc any update?

**Comment by rnc** [comment]
```
    @Test
    public void testInsert() throws Exception
    {
        Property filterable[] = new Property[1];
        filterable[0] = new Property();
        filterable[0].name = "EVENT_TIME";
        filterable[0].value = setup.getClientOrb().create_any();
        UtcT u = new UtcT(12, 34, (short) 56, (short) 78);
        UtcTHelper.insert(filterable[0].value, u);
        Any a = filterable[0].value;
        UtcTHelper.extract(a);
    }
```

Unit test works fine. From your stack trace it looks like you're using the Sun ORB rather than JacORB. Are you executing your program with `jaco` ?

**Comment by egcodes** [comment]
@rnc i execute this first "orbd -ORBInitialPort 1050" then my IRPAgent. How to run jaco. I did the installation, but it seemed there were too many configurations. In SunOrb, I'm just calling the command I wrote.
