### ISSUE TITLE
PortRangeSocketFactory::doCreateSocket

### ISSUE THREAD

**Issue by egleston** [JacORB/JacORB#208]
There is no distinction between `BindException` and `ConnectException` in the  `PortRangeSocketFactory::doCreateSocket` method, just a generic `IOException`.

If the `socket.bind()` is successful but the `socket.connect()` fails, the loop continues through the entire range of allowed ports.  Additionally, when this happens, there is a misleading `logger.warn` stating _Cannot bind socket between ports portMin and portMax to target host:port_.

[PortRangeSocketFactory.txt](https://github.com/JacORB/JacORB/files/1455621/PortRangeSocketFactory.txt)

**Comment by rnc** [comment]
Thanks for the report and the patch ( a pull request for the patch would be great!) Do you have a test case?

**Comment by rnc** [comment]
As both exceptions extend IOException (via SocketException) I think they both scenarios would exhibit the same behaviour. I am therefore going to close this. If you can provide a test case feel free to open a ticket.
