### ISSUE TITLE
Time.java hangs when the system time changes

### ISSUE THREAD

**Issue by nhoefer2** [JacORB/JacORB#210]
org.jacorb.util.Time.java has a method waitFor that wraps a Thread.sleep in a while loop. It looks as if it is checking to make sure the sleep has slept for at least the given time and repeats the difference if not.
Note that Thread.sleep is already guaranteed to sleep for at least the specified time, if not more (depending on the scheduler). 
The problem however is that if the system time changes backwards an hour while Thread.sleep is blocking, the difference between the calls to System.currentTimeMillis() is an hour and the next call to the Thread.sleep will sleep for an hour. This is because System.currentTimeMillis() is not monotonic time.

I believe just removing the while loop is sufficient since Thread.sleep already guarantees to sleep minimally for the specified time.

**Comment by rnc** [comment]
Huh that code hasn't been touched in years ;-) Yes System.currentTimeMillis is not monotonic (although System.nanoTime should be). 
Can you point me to where Thread.sleep "guarantees to sleep for minimally the specified time" - I can't see it in https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.3

**Comment by nhoefer2** [comment]
Well after I looked into it a bit further I found in "Concurrent Programming in Java" by Doug Lea, page 17, it says the following:

"Thread.sleep(long msecs) causes the current thread to suspend for at least msecs milliseconds."

Also, the documentation for TimeUnit.sleep(), which is just a wrapper for Thread.sleep, says roughly the same thing.
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html#sleep(long)

That being said, I reached out to Doug Lea for confirmation and here is his response:
"The hedging in the spec in part reflects that there are some
long-standing limitations on Windows in particular
in discovering that the system time changes, so you can't depend
on it."

Given his response, using nanoTime would probably be the best path forward.

**Comment by rnc** [comment]
@nhoefer2 Thanks for the investigation. Pull request (ideally with a test case!) would be very welcome.
