### ISSUE TITLE
Jacorb is not using newly added public keys to keystore, it requires ORB restart

### ISSUE THREAD

**Issue by alkasingheci** [JacORB/JacORB#215]

**Comment by alkasingheci** [comment]
I m programatically adding public keys to keystore and new keys doesnt take into affect by jacrob unless ORB is restarted.
Since my application has multiple users with multiple public keys, restarting JACORB is not feasible solution. Please suggest if there is some solution/workaround for this

**Comment by rnc** [comment]
I am not sure that is easily feasible without writing your own securitymanager/overriding trustmanager.

**Comment by alkasingheci** [comment]
Hi Nick,

Thanks for the response, I have no issue extending trustmanager.
Can you give me any pointer related to it?

Regards
Alka

**Comment by rnc** [comment]
I don't have any references I'm afraid.

**Comment by alkasingheci** [comment]
Hi Nick,

Can you let me know code reference in JACORB where the keystore is created/used.

Regards
Alka

**Comment by rnc** [comment]
Probably within  org.jacorb.security.ssl.sun_jsse,KeyStoreUtil.getKeyStore

**Comment by rnc** [comment]
I'm closing this issue ; I have no immediate plans to change JacORB's implementation but am willing to accept contributions :-)

**Comment by alkasingheci** [comment]
Hi Nick,

I haven’t got around to check the code. Is it ok if I can mail you here for any questions on JACORB code?

Regards
Alka

**Comment by rnc** [comment]
Ok ;-)
