### ISSUE TITLE
ArrayIndexOutOfBoundsException on create policy

### ISSUE THREAD

**Issue by nizinkin** [JacORB/JacORB#221]
Hello.
my code:
...

      ` any = orb.create_any();
        UtcT replyEndTime = org.jacorb.util.Time.corbaFuture (1000 * 1000);
        UtcTHelper.insert (any, replyEndTime);
        BidirectionalPolicyValueHelper.insert(any, BOTH.value);
        this.root_poa = (POA) orb.resolve_initial_references("RootPOA");
        this.root_poa.the_POAManager().activate();
        Policy[] policies = new Policy[4];
        policies[0] = root_poa.create_lifespan_policy(LifespanPolicyValue.TRANSIENT);
        policies[1] = root_poa.create_id_assignment_policy(IdAssignmentPolicyValue.SYSTEM_ID);
        policies[2] = root_poa.create_implicit_activation_policy(ImplicitActivationPolicyValue.IMPLICIT_ACTIVATION);
        policies[3] = orb.create_policy(BIDIRECTIONAL_POLICY_TYPE.value, any);
        this.bidir_poa = root_poa.create_POA("BiDirPOA", root_poa.the_POAManager(), policies);
        this.bidir_poa.the_POAManager().activate();
        
        Policy replyTimeOutPolicy = orb.create_policy(REPLY_END_TIME_POLICY_TYPE.value, any);`
...
at least row get exception
> java.lang.ArrayIndexOutOfBoundsException: 2
> 	at org.jacorb.orb.CDRInputStream._read4int(CDRInputStream.java:382)
> 	at org.jacorb.orb.CDRInputStream._read_long(CDRInputStream.java:404)
> 	at org.jacorb.orb.CDRInputStream.read_ulonglong(CDRInputStream.java:1426)
> 	at org.omg.TimeBase.UtcTHelper.read(UtcTHelper.java:62)
> 	at org.omg.TimeBase.UtcTHelper.extract(UtcTHelper.java:40)
> 	at org.jacorb.orb.policies.ReplyEndTimePolicy.<init>(ReplyEndTimePolicy.java:42)
> 	at org.jacorb.orb.ORB.create_policy(ORB.java:781)

I trying all methods to create policy to control reply execution, all return error

**Comment by nizinkin** [comment]
environment: linux mint 18.3  64-bit, jdk 1.8.0_161

**Comment by rnc** [comment]
You haven't mentioned which version of JacORB you are using?

I think you appear to be using the any in multiple different places - I think you need a separate any for the timing policy and for the bidrectionalpolicy. There are various existing tests such as src/test/java/org/jacorb/test/orb/connection/maxconnectionenforcement/MaxConnetcionEnforcementTest.java and src/test/java/org/jacorb/test/bugs/bugjac493/TimingTest.java which use BiDirPolicy and Timing Policies.

**Comment by nizinkin** [comment]
jacorb is last 3.9. I set another any, error is lost. but i can't set timeout for corba operations. call method do not return org.omg.CORBA.TIMEOUT.  My code:

       `anyForBidir = orb.create_any();
        anyForTimeOut = orb.create_any();
        anyForTimeOut.insert_ulonglong(1000*10000);
        BidirectionalPolicyValueHelper.insert(anyForBidir, BOTH.value);
        this.root_poa = (POA) orb.resolve_initial_references("RootPOA");
        this.root_poa.the_POAManager().activate();
        Policy[] policies = new Policy[4];
        policies[0] = root_poa.create_lifespan_policy(LifespanPolicyValue.TRANSIENT);
        policies[1] = root_poa.create_id_assignment_policy(IdAssignmentPolicyValue.SYSTEM_ID);
        policies[2] = root_poa.create_implicit_activation_policy(ImplicitActivationPolicyValue.IMPLICIT_ACTIVATION);
        policies[3] = orb.create_policy(BIDIRECTIONAL_POLICY_TYPE.value, anyForBidir);
        this.bidir_poa = root_poa.create_POA("BiDirPOA", root_poa.the_POAManager(), policies);
        this.bidir_poa.the_POAManager().activate();

        Policy replyTimeOutPolicy = orb.create_policy(RELATIVE_REQ_TIMEOUT_POLICY_TYPE.value, anyForTimeOut);
        Policy replyTimeOutPolicy1 = orb.create_policy(RELATIVE_RT_TIMEOUT_POLICY_TYPE.value, anyForTimeOut);
        orbService_new = ServiceHelper.narrow(orbService._set_policy_override( new Policy[] {replyTimeOutPolicy,replyTimeOutPolicy1},SetOverrideType.ADD_OVERRIDE));
        tmsService._release();
        orbService_new.long_running_method()`


log jacorb on long method
> INFO Using server ID (7762157763) for transient POA
INFO ClientConnectionManager: created new ClientGIOPConnection to xxx.xxx.xxx.xxx:0 (3f00a9f2)
FINE [0/1] creating new thread
FINE findPOA: reference generated by foreign POA [-1, 109, 99, 99, 45, 98, 105, 100, 105, 114, 45, 112, 111, 97, -2, -4, -74, -95, 91, 1, 0, 74, -68, 0, 0, 0, 0, 7] 
INFO Negotiated char codeset of UTF8 and wchar of UTF16
FINE created with invocationContext: {REQUEST_END_TIME=org.omg.TimeBase.UtcT@7a023076, REPLY_END_TIME=org.omg.TimeBase.UtcT@91d1166}
FINE Adding new retry group for xxx.xxx.xxx.xxx:0
FINE [0/2] removed idle thread (job scheduled)
FINE ClientGIOPConnection to xxx.xxx.xxx.xxx:0 (3f00a9f2): will wait until connected
FINE GIOPConnection.sendMessage timeout (millis): 996
FINE ClientGIOPConnection to xxx.xxx.xxx.xxx:0 (3f00a9f2): sendMessage() - opening transport org.jacorb.orb.iiop.ClientIIOPConnection@7147d0e7
FINE Selecting SSL for connection
FINE Trying to connect to xxx.xxx.xxx.xxx:9004 with timeout=996 using SSL.
INFO Connected to xxx.xxx.xxx.xxx:9004 from local port 47972 via SSL
FINE wrote 76 bytes to xxx.xxx.xxx.xxx:9004
FINE wrote 140 bytes to xxx.xxx.xxx.xxx:9004
FINE wrote 296 bytes to xxx.xxx.xxx.xxx:9004

without problem with server side all work fine, but
a want receive timeout exception after one second if server side no answer to client(in my case  i imitate problem on server side- server do not reseive message()).  I'm trying all examples in programming guide,what i do wrong?

**Comment by rnc** [comment]
The demo/policies directory contain some working examples of policies. If you are still having an issue, you can modify that to demonstrate your problem
