### ISSUE TITLE
Ever-growing number of ClientMessageReceptor threads waiting in GIOPConnection.waitUntilConnected

### ISSUE THREAD

**Issue by emkahfoursoft** [JacORB/JacORB#222]
I’m using Jacorb 3.7, but I have the same following problem with various versions since 2.3, so I don’t think it will be different in 3.8.

Anyway, I have a client/server application where the server opens a kind of callback channel to the client (but not using BiDi). In the server, there is a growing number of ClientMessageReceptor threads which are never closed, i.e., after a couple of weeks, there are thousands of them which slows down the server and finally leads to OutOfMemoryExceptions. I observed that in my production system there are 3 kinds of ClientMessageReceptor threads:

1. Threads waiting in org.jacorb.util.threadpool.ThreadPool.getJob: reasonable number of them, corresponds somehow to jacorb.connection.client.max_idle_receptor_threads

2. Threads waiting in org.jacorb.orb.etf.StreamConnectionBase.read: reasonable number of them, seems to be connections that are doing some work

3. Threads waiting in org.jacorb.orb.giop.GIOPConnection.waitUntilConnected: ever-growing number of them. These threads seem to do nothing and never go away.

Why? How can I tell those threads to finish? They are still there even if all the client applications are closed.

**Comment by rnc** [comment]
Do you call _release on your objects? Can you reproduce this in a test case?

**Comment by emkahfoursoft** [comment]
Yes, I call _release. How can I find out if I missed some object to call _release on?

I can reproduce this scenario in a test system by opening and closing a single client, but I haven't succeeded in extracting a small and simple test case to reproduce it.

**Comment by rnc** [comment]
Can you verify with 3.9 to double check please? Can you reproduce it with debug logging ? Are you creating multiple ORBs ?

**Comment by emkahfoursoft** [comment]
Sorry for the long delay. I re-did my test with Jacorb 3.9, the results were the same. I attached the jacorb log output at debug level as well as the jacorb.properties file I used and the ClientMessageReceptor-threads using jstack after the test.

I don't think I create multiple ORBs. How can I check this?

[jstack.txt](https://github.com/JacORB/JacORB/files/2620666/jstack.txt)
[jacorb.properties.txt](https://github.com/JacORB/JacORB/files/2620659/jacorb.properties.txt)
[debug.log](https://github.com/JacORB/JacORB/files/2620656/debug.log)

**Comment by emkahfoursoft** [comment]
Happy new year! Any news on this issue?

**Comment by alkasingheci** [comment]
Hi Nick,

I am also facing the same issue, is there any update on the issue? We do create multiple ORB. 

Regards
Alka

**Comment by rnc** [comment]
I haven't had time to look into this in detail. If you can provide a standalone compilable test case that would help immensely.

**Comment by alkasingheci** [comment]
I have thread dump of my system, when this issue occurred, will that help?
I dont when this issue occurs so cant provide concrete test case

**Comment by rnc** [comment]
Have you tried debugging it yourself ; I can give you some pointers if you want ?

**Comment by kvig** [comment]
I am running into this issue as well on 3.9. I can't tell what's not getting cleaned up, some debugging tips to track this down would be great.

**Comment by alkasingheci** [comment]
Hi Nick,

This so far has happened in deployment so cant debug it.

But please do provide pointers, I can check if it will help.

Regards
Alka

**Comment by emkahfoursoft** [comment]
+1 for tips on how to debug this problem

**Comment by kvig** [comment]
Here's what I found debugging my issue. My issue was the `ClientMessageReceptor` threads kept growing as I started and shutdown a specific server. When I got an event that the server started, I would connect to it and get its information. When I got the server stopped event, I would disconnect.

All the references I was aware of were released, but there were still some around that I didn't know about.  I found that the `ClientMessageReceptor` threads will not get cleaned up/reused unless all client connections are cleared for a given `org.jacorb.orb.giop.ClientConnection`(this is used by the delegates) - check the `client_count` variable on `ClientConnection`, it'll probably be 1 indicating that something missed getting released. You can call release on some of the CORBA objects, but if they haven't been used, they won't have incremented the `client_count` variable on that connection(that means there's still a different object you need to release).

To debug this, I was running in eclipse and set conditional breakpoints in `ClientConnection` on the `incClients()` and `decClients()` methods. The breakpoints would print a stack and then return false so I could proceed without without having to manually step each time. I had regular breakpoints on `Delegate::release()` where `bound=false;` is set to see which objects actually were getting removed. This was useful to verify that everything I knew about was getting released. It didn't help the parts that I didn't know about. 

I then got a heap dump using the `Memory Analysis`(MAT) tool added to Eclipse.  I showed the dominator tree for my heap dump and put in "ClientConnection" in the <Regex> field. Scrolling through the `ClientConnection`'s listed, Right click on any `ClientConnection` with a `client_count` value of 1(displayed in the lower left box) and select **List Objects** -> **With Incoming References**. I had entries with an array notation like [0], opening the connections, you'll see the delegate and you can drill down and find your local objects that still have that delegate.

Hope this is helpful.

**Comment by 23paras** [comment]
Hi Nick,
I was facing the same problem i.e. Threads waiting in org.jacorb.orb.giop.GIOPConnection.waitUntilConnected: ever-growing number of them. These threads seem to do nothing and never go away.

I have solved the problem by putting do_close=true  in the following code of  ClientGIOPConnection.java 

  /**
     * Closes the underlying transport, but keeps this ClientGIOPConnection
     * alive.  If, subsequently, another request is sent to this connection,
     * it will try to reopen the transport.
     */
    public void closeAllowReopen()
    {
        if (logger.isDebugEnabled())
        {
            logger.debug (this.toString() + ": closeAllowReopen()");
        }

        try
        {
            //Solve potential deadlock caused by COMM_FAILURE.
            //The strategy is getting write_lock before sync
            //connect_sync when you need both of them.
            getWriteLock(0);
            synchronized (connect_sync)
            {
                transport.close();
                **do_close=true;**
                // We expect that the same transport can be reconnected
                // after a close, something that the ETF draft isn't
                // particularly clear about.
            }
        }
        finally
        {
            releaseWriteLock();
        }
    }

Please let me know whether this will cause any other side effect or not .Any good suggestion will be helpfull .

Thanks
Paras Jain

**Comment by 23paras** [comment]
[wlrun70] FINE Adding new retry group for 172.18.213.122:6338
  [wlrun70] FINE GIOPConnection.sendMessage timeout (millis): 0
  [wlrun70] FINE ClientGIOPConnection to 172.18.213.122:6338 (17aa846c): sendMessage() - opening transport org.jacorb.orb.iiop.ClientIIOPConnection@3405e70f
  [wlrun70] FINE Selecting SSL for connection
  [wlrun70] FINE Trying to connect to 172.18.213.122:6338 with timeout=30000 using SSL.
  [wlrun70] FINE ClientIIOPConnection.createSocket to 172.18.213.122:6338 caught java.net.ConnectException: Connection refused
  [wlrun70] FINE ClientGIOPConnection to 172.18.213.122:6338 (17aa846c): sendMessage() -- failed to open transport
  [wlrun70] FINE invoke[-->]: SystemException
  [wlrun70] org.omg.CORBA.TRANSIENT: Retries exceeded, couldn't reconnect to 172.18.213.122:6338  vmcid: 0x0  minor code: 0  completed: No
  [wlrun70]     at org.jacorb.orb.iiop.ClientIIOPConnection.connect(ClientIIOPConnection.java:224)
  [wlrun70]     at org.jacorb.orb.giop.GIOPConnection.sendMessage(GIOPConnection.java:1075)
  [wlrun70]     at org.jacorb.orb.giop.GIOPConnection.sendRequest(GIOPConnection.java:1020)
  [wlrun70]     at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:309)
  [wlrun70]     at org.jacorb.orb.giop.ClientConnection.sendRequest(ClientConnection.java:290)
  [wlrun70]     at org.jacorb.orb.Delegate._invoke_internal(Delegate.java:1373)
  [wlrun70]     at org.jacorb.orb.Delegate.invoke_internal(Delegate.java:1210)
  [wlrun70]     at org.jacorb.orb.Delegate.invoke(Delegate.java:1197)
  [wlrun70]     at org.jacorb.orb.dii.Request._invoke(Request.java:316)
  [wlrun70]     at org.jacorb.orb.dii.Request.access$000(Request.java:46)
 [wlrun70] FINE Delegate._invoke_internal: Not looping on org.omg.CORBA.TRANSIENT: Retries exceeded, couldn't reconnect to 172.18.213.122:6338  vmcid: 0x0  minor code: 0  completed: No
  [wlrun70] FINE Delegate._invoke_internal: closing connection due to org.omg.CORBA.TRANSIENT: Retries exceeded, couldn't reconnect to 172.18.213.122:6338  vmcid: 0x0  minor code: 0  completed: No
  [wlrun70] FINE release the connection
  [wlrun70] FINE ClientConnectionManager: cannot release ClientGIOPConnection to 172.18.213.122:6338 (17aa846c) (still has 1 client(s))
  [wlrun70] FINE ClientConnectionManager: releasing ClientGIOPConnection to 172.18.213.122:6338 (17aa846c)
  [wlrun70] FINE ClientGIOPConnection to 172.18.213.122:6338 (17aa846c): close()
  [wlrun70] FINE [1/1] job queue empty
  [wlrun70] FINE DII Request caught Exception



This is the error log which i am getting

**Comment by rnc** [comment]
@23paras Without reproducing a particular problem to validate that change I wouldn't want to merge it in.

@kvig Thanks for an excellent break down!

@emkahfoursoft  @alkasingheci  Currently I think the logging will not help your scenario ; instead as @kvig's  suggestions are worth looking at. My other thought would be to use a Byteman ( http://byteman.jboss.org ) script to trace in your application the incoming connections to help find the missing reference.

**Comment by 23paras** [comment]
@rnc 
I compared the code between ServerGIOPConnection and ClientGIOPConnection .I found one difference i.e in  ServerGIOPConnection do_close is  set to true in sendCloseConnection  so anything waiting in waitUntilConnection  doesn't think there is a possibility of connecting.But in ClientGIOPConnection nowhere do_close is set to true (apart from streamClosed )so there is always waiting thread in waitUntilConnection  .it expect that the same transport can be reconnected
after a close.
If any Exception with org.omg.CORBA.TRANSIENT in connecting the transport in sendMessage in that case there will always  be a hanging thread in waitUntilConnection  .These threads continuously increased if we try to connect again and it fail with the same org.omg.CORBA.TRANSIENT.I hope it will be helpful .

thanks

**Comment by emkahfoursoft** [comment]
I finally solved this issue. After all, it was just missing _release calls, just like @rnc suggested his first reply ;-) In hindsight, I could have found them just like @kvig described:

> I then got a heap dump using the Memory Analysis(MAT) tool added to Eclipse. I showed the dominator tree for my heap dump and put in "ClientConnection" in the field. Scrolling through the ClientConnection's listed, Right click on any ClientConnection with a client_count value of 1(displayed in the lower left box) and select List Objects -> With Incoming References. I had entries with an array notation like [0], opening the connections, you'll see the delegate and you can drill down and find your local objects that still have that delegate.

Note that jvisualvm, which comes free with the JDK, did the job just as well for me: While the application was running, I created a heap dump, filtered for ClientConnection instances, looked at the references, opened each "[0]" ClientConnection array, then the "connections" field of the Delegate class, and then the _delegate field (ignoring the instances of org.jacorb.org.Reference) showed me the instance which I forgot to call _release on.

What made the problem so difficult for me to solve, was the fact that I didn't know exactly how my application worked and how JacORB works internally (e.g. the different behavior of threads waiting in org.jacorb.orb.etf.StreamConnectionBase.read vs. threads waiting in org.jacorb.orb.giop.GIOPConnection.waitUntilConnected). Debugging my application including the JacORB source helped me a lot here.

**Comment by 23paras** [comment]
@rnc 
@alkasingheci 
Hi ,
I am facing one problem in jacorb -

org.omg.CORBA.COMM_FAILURE: IOException: java.net.SocketException: Socket closed  vmcid: 0x0  minor code: 0  completed: No
	at org.jacorb.orb.etf.ConnectionBase.to_COMM_FAILURE(ConnectionBase.java:153)
	at org.jacorb.orb.iiop.IIOPConnection.handleCommFailure(IIOPConnection.java:79)
	at org.jacorb.orb.etf.StreamConnectionBase.flush(StreamConnectionBase.java:227)
	at org.jacorb.orb.giop.ServerGIOPConnection.sendCloseConnection(ServerGIOPConnection.java:152)
	at org.jacorb.orb.giop.ServerGIOPConnection.tryClose(ServerGIOPConnection.java:97)
	at org.jacorb.orb.giop.GIOPConnectionManager.shutdown(GIOPConnectionManager.java:228)
	at org.jacorb.orb.ORB.shutdown(ORB.java:2386)

Here it is showing socket is closed but it is not releasing the port properly. It is close_wait state .Please suggest what do to in oreder to fix this problem .

Thanks
Paras jain

**Comment by rnc** [comment]
@23paras This is a closed ticket - it may be better for you to open a separate one? Can you provide a test case reproducing the problem?
