### ISSUE TITLE
Non-string values in Properties objects passed to directly to ORB.init() are silently ignored

### ISSUE THREAD

**Issue by matt-watson90** [JacORB/JacORB#224]
The setAttributes method in the JacORBConfiguration will silently ignore any non-string properties: 

```
    /**
     * set attributes of this configuration using properties.
     *
     * @param properties the new attributes
     */

    @Override
    public void setAttributes(Properties properties)
    {
        // Some lunatics illegally put non String objects into System props
        // as keys / values - we ignore them.
        Iterator<String> keyIt = properties.stringPropertyNames().iterator();
        while (keyIt.hasNext())
        {
            String key = keyIt.next();
            setAttribute(key, properties.getProperty(key));
        }
    }
```

Not using them makes sense since the JavaDoc for Properties says that non-string values are strongly discouraged. However ignoring them silently seems like a way to introduce subtle bugs that aren't easily spotted. Since Java will quite happily let you add an int or a Bool to a Properties object and the only way you'll realise that your property hasn't been applied is when you don't see the expected behaviour.

We had the following code, which didn't prompt any suspicion until we realised that our timeouts weren't working:

        Properties properties = new Properties();
        properties.put("org.omg.CORBA.ORBClass", orbImpl);
        properties.put("jacorb.use_timer_queue", true);
        properties.put("jacorb.connection.request.write_timeout", 60000);

        orb = ORB.init(new String[0], properties);

If a warning had been logged (or an Exception thrown) when the 'bad' properties were encountered this would have been a lot easier to spot.

**Comment by rnc** [comment]
Yeah makes sense to print warning (or attempt to convert). If you can send a PR (ideally with test) then I'd be happy to take a look

**Comment by matt-watson90** [comment]
Let me see what I can put together over the next couple of days.
