### ISSUE TITLE
jaco script does not process arguments properly

### ISSUE THREAD

**Issue by Archangelix** [JacORB/JacORB#225]
An example can be seen via lsns script.

Calling this command below:
`lsns -f /tmp/test_output.txt`

will produce this output:
```jaco is a wrapper around sometimes long jvm command lines
All arguments except the following are passed through to the jvm command line
-rdbg            Adds arguments to enable remote debugging via port 5005
-dbgport [port]  also enables remote debugging via the supplied port
```
It's because the switch case '?' is not escaped that the lsns arguments, i.e. "-f /tmp/test_output.txt" is consumed at the wrong case branch.

Instead of using:
`-?)`

it should be:
`-\?)`

Can I make the PR?

**Comment by rnc** [comment]
@Archangelix  Good spot! PRs very welcome :-)

**Comment by Archangelix** [comment]
Hi @rnc , this will be my first PR. If you don't mind I need some guidance.

I have created a new branch "jaco-escape-question-mark" and committed my code change here, but somehow I can't push it.
> remote: Permission to JacORB/JacORB.git denied to Archangelix.
> fatal: unable to access 'https://github.com/JacORB/JacORB.git/': The requested URL returned error: 403

Is there anything  I need to set up in JacORB repo?

**Comment by rnc** [comment]
@Archangelix Sure :-) Did you read https://github.com/JacORB/JacORB/blob/master/CONTRIBUTING.md#creating-a-pull-request-on-github ? Have you forked the repository (inside github, the fork button) and then you push to your copy, and issue the PR via the github interface.

**Comment by Archangelix** [comment]
I've just submitted the PR, but it seems the Travis CI is failing. I have checked the CI build log but I don't quite get what's happening.
```
Installing openjdk7

$ export JAVA_HOME=~/openjdk7

$ export PATH="$JAVA_HOME/bin:$PATH"

$ ~/bin/install-jdk.sh --target "/home/travis/openjdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "GPL" --cacerts

Ignoring license option: GPL -- using GPLv2+CE by default

install-jdk.sh 2019-09-17

Expected feature release number in range of 9 to 14, but got: 7

The command "~/bin/install-jdk.sh --target "/home/travis/openjdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "GPL" --cacerts" failed and exited with 3 during .

```

Some certificate issue, apparently. Is there any suggestion what I can do now?

**Comment by rnc** [comment]
@Archangelix  Looks like Travis have stopped accepting openjdk7 ; I've just pushed a change to switch to 8.

**Comment by Archangelix** [comment]
Ah, alright then. Thanks! :)
