### ISSUE TITLE
AppScan issue Common API Call: PrivilegeEscalation

### ISSUE THREAD

**Issue by nguyensha** [JacORB/JacORB#239]
Hi 
I got issue about Common API Call: PrivilegeEscalation when I run AppScan for our app

Common API Call: PrivilegeEscalation: java.lang.reflect.Method.invoke(Object;Object[]):Object IRServer:76

I captures AppScan as below
![image](https://user-images.githubusercontent.com/5946060/102612636-aaea9480-4163-11eb-8410-179711117133.png)

Please help to support.

**Comment by rnc** [comment]
The Interface Repository uses reflection look up classes/types. I would imagine you would need clarify why this is an issue within the tool you are using.
