### ISSUE TITLE
EOLed picocontainer-1.2 with latest JacORB

### ISSUE THREAD

**Issue by zipsantro** [JacORB/JacORB#289]
We currently consume JacORB version 3.9. It contains picocontainer-1.2.jar which has been EOLed. I believe there is no active development happening in this library. So, are there any plans to get away with picocontainer in JacORB or could we expect the latest version of this library in the upcoming releases?

**Comment by rnc** [comment]
You are correct there isn't any development happening on the 1.x, 2.x or 3.x line. The core ORB does not use picocontainer ; only the Notification service and that uses an old version as you mentioned. Apart from the age of that aforementioned code, is there a particular reason you wanted a different version?

**Comment by zipsantro** [comment]
Within our org, we perform a regular checks on the list of EOLed libraries/sdk that we ship with our product. Picocontainer has been flagged by that process as one of aged/EOLed. We ship picocontainer as it is part of JacORB SDK and our product doesn't directly consume it in any way. So, would it be viable to just remove picocontainer and expect that JacORB will work without any issue?

**Comment by rnc** [comment]
What part of JacORB do you use (i.e. core orb, services etc?) Out of pure curiosity, if its allowed :-) , what is your product/org?

**Comment by zipsantro** [comment]
Just to clarify more, I referred to package java\jacorb-services.jar!\org\jacorb\notification and assumes that picocontainer is only used here. If that's the case, we are not using "notification" in anyway in our product. 
I am afraid to share the product/org details here.

**Comment by rnc** [comment]
Ok. As mentioned picocntainer is not used in the core
